Update retry

diff --git a/retry b/retry
--- a/retry
+++ b/retry
@@ -286,3 +286,100 @@ spec:
     - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME !~ /^Release.*/ && $FORTIFY_SCAN == "true"'
     - if: '$CI_PIPELINE_SOURCE == "api" && $FORTIFY_SCAN == "true"'
 
+
+
+
+errro----
+
+spec:
+  inputs:
+    JOBNAME:
+      default: run_fortify_scan
+      description: 'REQUIRED: Job name for Fortify Scan'
+    STAGE:
+      default: fortify_scan
+      description: 'REQUIRED: Stage name for this job'
+    IMAGE:
+      default: $FORTIFY_IMG
+      description: 'REQUIRED: Docker image to use for Fortify Scan'
+    APPLICATION_NAME:
+      default: $MY_FORTIFY_SSC_APP
+      description: 'REQUIRED: Fortify SSC Application Name'
+    VERSION_NAME:
+      default: $MY_FORTIFY_SSC_PV
+      description: 'REQUIRED: Fortify SSC Version Name'
+    FORTIFY_SSC_URL:
+      default: $FORTIFY_SSC_URL
+      description: 'REQUIRED: Fortify SSC URL'
+    FORTIFY_SSC_TOKEN:
+      default: $FORTIFY_SSC_TOKEN
+      description: 'REQUIRED: Fortify SSC Token'
+    SCAN_OPTIONS:
+      default: "--log-file $CI_PROJECT_DIR/fortify.log --output-file $CI_PROJECT_DIR/fortify.fpr"
+      description: 'Optional: Additional scan options'
+    SCAN_TARGET:
+      default: "target"
+      description: 'REQUIRED: Specify the target to scan, either "service" or "ui" or any target directory'
+
+---
+
+"$[[ inputs.JOBNAME ]]":
+  stage: $[[ inputs.STAGE ]]
+  image: $[[ inputs.IMAGE ]]
+  environment: $ENV
+  needs:
+    - job: build-jar  # This ensures the scan runs after the build job
+  script:
+    - echo "Starting Fortify scan for $[[ inputs.SCAN_TARGET ]]"
+    - export SCANCENTRAL_LOG="$CI_PROJECT_DIR"
+    - export RC=0
+    - |
+      if [ "$[[ inputs.SCAN_TARGET ]]" == "service" ]; then
+        cd $CI_PROJECT_DIR/servicefolder  # Change to service folder
+      elif [ "$[[ inputs.SCAN_TARGET ]]" == "ui" ]; then
+        cd $CI_PROJECT_DIR/uifolder  # Change to UI folder
+      elif ["$[[ inputs.SCAN_TARGET ]]" == "target" ]; then
+        cd $CI_PROJECT_DIR/target 
+      else
+        echo "Unknown scan target: $[[ inputs.SCAN_TARGET ]]"
+        exit 1
+      fi
+    - scancentral -sscurl "$[[ inputs.FORTIFY_SSC_URL ]]" -ssctoken $[[ inputs.FORTIFY_SSC_TOKEN ]] start -sargs "$EXCLUDE_ARGS $MY_FORTIFY_SQL_PARAMETER" -targs "--build-label $[[ inputs.VERSION_NAME ]] $EXCLUDE_ARGS $MY_FORTIFY_SQL_PARAMETER" -exclude '**/**/*.pfx' -exclude '**/**/*.jks' -exclude 'settings.xml' -upload -application "$[[ inputs.APPLICATION_NAME ]]" -version $[[ inputs.VERSION_NAME ]] -uptoken "$[[ inputs.FORTIFY_SSC_TOKEN ]]" $SCANCENTRAL_BUILD_OPTS $[[ inputs.SCAN_OPTIONS ]] --save-package filesscanned.zip 2> scancentral.err || RC=$?
+    - echo "Result from Fortify scan - $RC"
+    - ls -lart $CI_PROJECT_DIR  # List project directory to debug
+    - if [ -f "$CI_PROJECT_DIR/scancentral.log" ]; then cat $CI_PROJECT_DIR/scancentral.log; fi  # Display logs if exists
+  rules:
+    - if: '$CI_PIPELINE_SOURCE == "schedule" && $FORTIFY_SCAN == "true"'
+    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^main/ && $FORTIFY_SCAN == "true"'
+    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME !~ /^Release.*/ && $FORTIFY_SCAN == "true"'
+    - if: '$CI_PIPELINE_SOURCE == "api" && $FORTIFY_SCAN == "true"'
+
+
+
+
+
+
+
+
+
+
+
+
+Created fresh repository.
+Checking out 02c7887e as detached HEAD (ref is cicd-scan-files)...
+Skipping Git submodules setup
+Downloading artifacts
+00:01
+Downloading artifacts for build-jar (14226896)...
+Downloading artifacts from coordinator... ok        host=gitlab.onefiserv.net id=14226896 responseStatus=200 OK token=glcbt-64
+Executing "step_script" stage of the job script
+00:01
+$ echo "Starting Fortify scan for service"
+Starting Fortify scan for service
+$ export SCANCENTRAL_LOG="$CI_PROJECT_DIR"
+$ export RC=0
+$ if [ "service" == "service" ]; then # collapsed multi-line command
+/scripts-49649-14227288/step_script: line 229: cd: /builds/mstechpe/shared-apps/java17_template_port9000/servicefolder: No such file or directory
+Cleaning up project directory and file based variables
+00:00
+ERROR: Job failed: command terminated with exit code 1
